#!/bin/bash
#

module load python
export PYTHONPATH=/home/mac732/.local/lib/python3.12/site-packages:$PYTHONPATH

#
workerdir=worker$1
#
mkdir -p $workerdir
#
cp -r template_inner.tar.gz $workerdir/
#
cd $workerdir/
#
tar -xzf template_inner.tar.gz
#
cd template_inner/

./pestpp-mou pest/prams_bbgo.pst /H c059:4020
